name: deploy Storybook and publish to npm

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install

      - name: Linter
        run: npm run lint

      - name: Synchronize version with npm
        run: |
          CURRENT_VERSION=$(npm view socraft-ui version)
          echo "Current version on npm: $CURRENT_VERSION"
          npm version $CURRENT_VERSION --no-git-tag-version

      - name: Increment version
        run: npm version patch --no-git-tag-version

      - name: Build Storybook
        run: npx storybook build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
